#!/usr/bin/env bash

set -eu

SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
source ${SCRIPT_DIR}/util/relayer-util

rm -rf ${RELAYER_CONF} &> /dev/null

ID=${1:-0}

jq "((.src, .dst).\"client-id\" |= \"mock-client-$ID\") | ((.src, .dst).\"connection-id\" |= \"connection-$ID\")" < ${CONF_DIR}/path.json > ${CONF_DIR}/path-x.json
mv ${CONF_DIR}/path-x.json ${CONF_DIR}/path.json

${RLY} config init
${RLY} chains add-dir ${CONF_DIR}/chains/

# add a path between chain0 and chain1
$RLY paths add $CHAINID_ONE $CHAINID_TWO $PATH_NAME --file=${CONF_DIR}/path.json
