#!/bin/bash

set -eux

source $(cd $(dirname "$0"); pwd)/../../../scripts/util

SCRIPT_DIR=$(cd $(dirname $0); pwd)
FIXTURES_DIR=${SCRIPT_DIR}/../fixtures

RELAYER_CONF="$HOME/.yui-relayer"
RLY_BINARY=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BINARY} --debug"

PATH_NAME=ibc01

# back up the original connection identifiers
srcOrigConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].src."connection-id"')
dstOrigConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].dst."connection-id"')

# back up the original config.json and make connection identifiers empty
origconfig=`mktemp`
cp "$RELAYER_CONF/config/config.json" $origconfig
$RLY paths edit $PATH_NAME src connection-id ''
$RLY paths edit $PATH_NAME dst connection-id ''

# create a new connection and save the new connection identifiers
$RLY tx connection $PATH_NAME
srcConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].src."connection-id"')
dstConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].dst."connection-id"')

# resume the original config.json
mv $origconfig "$RELAYER_CONF/config/config.json"

# constant variables
APP_ADDRESS=`cat ${FIXTURES_DIR}/ethereum/ibc1/addresses/IBCChannelUpgradableMockApp`
#TIMEOUT_FLAGS="--timeout-height 0-100000000 --timeout-timestamp `date -d 2030/01/01 +%s`"
TIMEOUT_FLAGS="--timeout-height 0-100000000"

# test channel upgrade (crossing-hello)
UPGRADE_FIELDS_FLAGS_A="--ordering ORDER_ORDERED --connection-hops $srcConnectionId --version mockapp-2"
UPGRADE_FIELDS_FLAGS_B="--ordering ORDER_ORDERED --connection-hops $dstConnectionId --version mockapp-2"
$RLY tx channel-upgrade init ibc01 ibc0 $UPGRADE_FIELDS_FLAGS_A
$RLY eth upgrade propose ibc01 ibc1 --app-address $APP_ADDRESS $UPGRADE_FIELDS_FLAGS_B $TIMEOUT_FLAGS
$RLY tx channel-upgrade init ibc01 ibc1 $UPGRADE_FIELDS_FLAGS_B
$RLY tx channel-upgrade execute ibc01 --until-flushing
$RLY eth upgrade allow ibc01 ibc1 --app-address $APP_ADDRESS --upgrade-sequence 1
$RLY tx channel-upgrade execute ibc01

# test channel upgrade (non-crossing-hello)
UPGRADE_FIELDS_FLAGS_A="--ordering ORDER_UNORDERED --connection-hops $srcOrigConnectionId --version mockapp-3"
UPGRADE_FIELDS_FLAGS_B="--ordering ORDER_UNORDERED --connection-hops $dstOrigConnectionId --version mockapp-3"
$RLY tx channel-upgrade init ibc01 ibc0 $UPGRADE_FIELDS_FLAGS_A
$RLY tx channel-upgrade init ibc01 ibc0 $UPGRADE_FIELDS_FLAGS_A
$RLY eth upgrade propose ibc01 ibc1 --app-address $APP_ADDRESS $UPGRADE_FIELDS_FLAGS_B $TIMEOUT_FLAGS
$RLY tx channel-upgrade init ibc01 ibc1 $UPGRADE_FIELDS_FLAGS_B
$RLY tx channel-upgrade execute ibc01 --until-flushing
$RLY eth upgrade allow ibc01 ibc1 --app-address $APP_ADDRESS --upgrade-sequence 3
$RLY tx channel-upgrade execute ibc01

# test channel upgrade cancel
UPGRADE_FIELDS_FLAGS_A="--ordering ORDER_ORDERED --connection-hops $srcConnectionId --version mockapp-4"
UPGRADE_FIELDS_FLAGS_B="--ordering ORDER_ORDERED --connection-hops $dstConnectionId --version mockapp-4"
$RLY tx channel-upgrade init ibc01 ibc0 $UPGRADE_FIELDS_FLAGS_A
$RLY eth upgrade propose ibc01 ibc1 --app-address $APP_ADDRESS $UPGRADE_FIELDS_FLAGS_B $TIMEOUT_FLAGS
$RLY tx channel-upgrade init ibc01 ibc1 $UPGRADE_FIELDS_FLAGS_B
$RLY tx channel-upgrade cancel ibc01 ibc0  # create situation where ibc0.error_receipt.sequence >= ibc1.channel.upgrade_sequence
$RLY tx channel-upgrade execute ibc01      # the channel upgrade of ibc1 should be cancelled
