#!/bin/bash

set -eux

SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
FIXTURES_DIR=${SCRIPT_DIR}/../fixtures

RELAYER_CONF="$HOME/.yui-relayer"
RLY_BINARY=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BINARY} --debug"

PATH_NAME=ics20-path

TM_ADDRESS=$(${RLY} tendermint keys show ibc0 testkey)
BOB_INDEX=2

ADDRESSES_DIR_B="${FIXTURES_DIR}/ethereum/ibc1/addresses"
ICS20_TRANSFER_BANK_CONTRACT_B=`cat ${ADDRESSES_DIR_B}/ICS20TransferBank`

MNEMONIC_B=$($RLY config show | jq -r '.chains[] | select(.chain.chain_id == "ibc1").chain.signer.mnemonic')
RPC_ADDRESS_B=$($RLY config show | jq -r '.chains[] | select(.chain.chain_id == "ibc1").chain.rpc_addr')
PORT_B=$($RLY paths list --json | jq -r --arg path $PATH_NAME '.[$path].dst."port-id"')
CHANNEL_B=$($RLY paths list --json | jq -r --arg path $PATH_NAME '.[$path].dst."channel-id"')
ETH_ADDRESS_B=$(cast wallet address --mnemonic "$MNEMONIC_B" --mnemonic-index $BOB_INDEX)

DENOM_A=samoleans
DENOM_B="${PORT_B}/${CHANNEL_B}/${DENOM_A}"

TX_INTERVAL=3

echo "!!! ibc0 -> ibc1 !!!"
${RLY} tx transfer $PATH_NAME ibc0 ibc1 "100${DENOM_A}" $ETH_ADDRESS_B
sleep ${TX_INTERVAL}
${RLY} tx relay $PATH_NAME --src-seqs 1
sleep ${TX_INTERVAL}
${RLY} tx acks $PATH_NAME --dst-seqs 1
sleep ${TX_INTERVAL}

echo "!!! ibc1 -> ibc0 !!!"
cast send \
     --rpc-url $RPC_ADDRESS_B \
     --mnemonic "$MNEMONIC_B" \
     --mnemonic-index ${BOB_INDEX} \
     $ICS20_TRANSFER_BANK_CONTRACT_B \
     'sendTransfer(string,uint256,string,string,string,uint64)' \
     $DENOM_B \
     100 \
     $TM_ADDRESS \
     $PORT_B \
     $CHANNEL_B \
     100000
sleep ${TX_INTERVAL}
${RLY} tx relay $PATH_NAME --dst-seqs 1
sleep ${TX_INTERVAL}
${RLY} tx acks $PATH_NAME --src-seqs 1
